### ISSUE TITLE
[Question] Is this compatible with Maud templating?

### ISSUE THREAD

**Issue by fraschm1998** [wainwrightmark/capacitor_bindings#2]
Title. Is capacitor compatible with [Maud](https://github.com/lambda-fairy/maud) templating? As it has the html in the rust files and not in .html

**Comment by wainwrightmark** [comment]
I'm afraid I've not used Maud, but looking at the documentation for it, it seems to be intended for Server Side Rendering. This crate will not work in that context - it's designed for IOS/Android apps that use client side rendering. 

Web frameworks like [Yew ](https://yew.rs/)and [Leptos ](https://github.com/leptos-rs/leptos) have similar macros which can be used for CSR and both are compatible with this. 


Does that answer your question? I may have misunderstood what Maud does. If you let me know what you're trying to achieve I might be able to offer more guidance.
